[server]
interface = "127.0.0.1"
port = "8084"
# The "redirect" host ist used to build the callback URL, which is used by Keycloak to redirect back to the Tresor backend
# This is especially important in Dockerized environments, when the user and applications routing tables differ
# NOTE: in Keycloak allowed redirect URLs have to be configured and "localhost" is not the same as "127.0.0.1" in this context!
redirecthost = "127.0.0.1"
# cookiemasterkey is used to derive the cryptographical keys for cookie encryption.
# As long as this key does not change, client side session data will be accessable by the server.
# Set a new cookie_master_key before starting the application that MUST be >= 32 CHARS to offer strong encryption!
cookiemasterkey = "jcudf//DCfdk78345dDUCB23$$diehCV"

[database]
host = "localhost"
user = "postgres"
pass = "aintsecure"

[auth]
# The following configuration refers to the Keycloak instance used for authentication/authorization
host = "localhost"
port = "8080"
realm = "tresor"
# The "redirect" host ist used to build the auth_url, which is used for the /login route redirect to keycloak
# This is especially important in Dockerized environments, when the user and applications routing tables differ
redirecthost = "localhost"
# the clientid is a public identifier against the OIDC-provider but should not be guessable by third parties.
clientid = "tresor-backend"
# client_secret is only known to OIDC-provider and the application and must be kept confidential.
# Set a new random key >= 32 CHARS before starting the application!
clientsecret = "8cHU783LSC839uhapouji3dHJ34N32SC"
scope = "tresor"

[logging]
level = "info"
